apiVersion: v1
kind: Secret
metadata:
  name: common-secret
  namespace: spring-cloud-msa
type: Opaque
data:
  # MySQL 인증정보 (base64 encoded)
  mysql-username: cm9vdA==  # root
  mysql-password: cm9vdDEyMw==  # root123
  
  # RabbitMQ 인증정보 (base64 encoded)
  rabbitmq-username: YWRtaW4=  # admin
  rabbitmq-password: YWRtaW4xMjM=  # admin123